version: "3"
services:
  server:
    build:
      context: .
      dockerfile: greet/greet_server/Dockerfile
    restart: always
    ports:
      - "50051:50051"
  client:
    build:
      context: .
      dockerfile: greet/greet_client/Dockerfile
    restart: always
    links:
      - server
    depends_on:
      - server